---
# defaults file for deploy_adguard
deploy_adguard_directory: /opt/adguard
deploy_adguard_timezone: "Europe/Paris"
deploy_adguard_enable_admin_interface: true
deploy_adguard_enable_dhcp: false
deploy_adguard_enable_doh: true
deploy_adguard_enable_dot: false
deploy_adguard_enable_doq: false
deploy_adguard_enable_dnscrypt: false
deploy_adguard_start_service: false
deploy_adguard_virtual_ip:
  enable: true
  interface: eth0
  vip_addr: "192.168.1.53"
deploy_adguard_node_exporter:
  enable: true
  protocol: http
  port: 80
  username: admin
  password: password
  exporter_port: 9617
  interval: 10s
  log_limit: 10000
deploy_adguard_consul:
  enable: false
  consul_addr: http://127.0.0.1:8500
  consul_token: someUUIDhere
  configuration:
    service:
      name: adguard
      address: "{{ ansible_default_ipv4.address }}"
      port: 80
      tags: []
      connect:
        sidecar_service: {}
deploy_adguard_config: {}
